import { CameraFeed, IdentifiedPerson, SecurityAlert } from '@/types/caca';

export const INITIAL_CAMERAS: CameraFeed[] = [
  {
    id: 'cam-01',
    name: 'CAM 01',
    location: 'Escritório Principal',
    status: 'online',
    personsCount: 9,
    fps: 30,
    resolution: '1080p',
    activeActivity: 'Trabalhando',
    thumbnailUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=400&auto=format&fit=crop&q=80',
  },
  {
    id: 'cam-02',
    name: 'CAM 02',
    location: 'Sala de Reunião',
    status: 'online',
    personsCount: 2,
    fps: 30,
    resolution: '1080p',
    activeActivity: 'Reunião',
    thumbnailUrl: 'https://images.unsplash.com/photo-1517502884422-41eaead166d4?w=400&auto=format&fit=crop&q=80',
  },
  {
    id: 'cam-03',
    name: 'CAM 03',
    location: 'Entrada / Recepção',
    status: 'online',
    personsCount: 1,
    fps: 30,
    resolution: '1080p',
    activeActivity: 'Caminhando',
    thumbnailUrl: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=400&auto=format&fit=crop&q=80',
  },
  {
    id: 'cam-04',
    name: 'CAM 04',
    location: 'Área Comum',
    status: 'online',
    personsCount: 0,
    fps: 30,
    resolution: '1080p',
    activeActivity: 'Livre',
    thumbnailUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=400&auto=format&fit=crop&q=80',
  },
];

export const INITIAL_PERSONS: IdentifiedPerson[] = [
  {
    id: 'p-1',
    name: 'Lucas Mendes',
    role: 'Funcionário',
    department: 'Engenharia de Software',
    entryTime: '14:26',
    location: 'Recepção',
    confidence: 0.98,
    status: 'present',
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    badgeId: 'CR-9042',
    detectionsCountToday: 14,
  },
  {
    id: 'p-2',
    name: 'Ana Souza',
    role: 'Gerente',
    department: 'Operações e Projetos',
    entryTime: '14:25',
    location: 'Escritório Principal',
    confidence: 0.97,
    status: 'present',
    photoUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200&auto=format&fit=crop&q=80',
    badgeId: 'CR-8120',
    detectionsCountToday: 22,
  },
  {
    id: 'p-3',
    name: 'Carlos Lima',
    role: 'Analista Sênior',
    department: 'Segurança & Infraestrutura',
    entryTime: '14:24',
    location: 'Escritório Principal',
    confidence: 0.96,
    status: 'present',
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    badgeId: 'CR-7319',
    detectionsCountToday: 18,
  },
  {
    id: 'p-4',
    name: 'Mariana Silva',
    role: 'Coordenadora',
    department: 'Recursos Humanos',
    entryTime: '14:23',
    location: 'Sala de Reunião',
    confidence: 0.98,
    status: 'present',
    photoUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&auto=format&fit=crop&q=80',
    badgeId: 'CR-6204',
    detectionsCountToday: 9,
  },
  {
    id: 'p-5',
    name: 'Rodrigo Santos',
    role: 'Engenheiro',
    department: 'Engenharia de Software',
    entryTime: '13:58',
    location: 'Escritório Principal',
    confidence: 0.95,
    status: 'present',
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80',
    badgeId: 'CR-5541',
    detectionsCountToday: 12,
  },
  {
    id: 'p-6',
    name: 'Juliana Costa',
    role: 'Desenvolvedora',
    department: 'Engenharia de Software',
    entryTime: '13:45',
    location: 'Escritório Principal',
    confidence: 0.96,
    status: 'present',
    photoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&auto=format&fit=crop&q=80',
    badgeId: 'CR-4190',
    detectionsCountToday: 16,
  },
  {
    id: 'p-7',
    name: 'Felipe Rocha',
    role: 'Product Designer',
    department: 'Design de Produto',
    entryTime: '13:30',
    location: 'Escritório Principal',
    confidence: 0.94,
    status: 'present',
    photoUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=200&auto=format&fit=crop&q=80',
    badgeId: 'CR-3281',
    detectionsCountToday: 8,
  },
  {
    id: 'p-8',
    name: 'Beatriz Ramos',
    role: 'Cientista de Dados',
    department: 'Inteligência Artificial',
    entryTime: '13:15',
    location: 'Escritório Principal',
    confidence: 0.97,
    status: 'present',
    photoUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&auto=format&fit=crop&q=80',
    badgeId: 'CR-2195',
    detectionsCountToday: 19,
  },
];

export const INITIAL_ALERTS: SecurityAlert[] = [
  {
    id: 'alt-1',
    timestamp: '14:15',
    type: 'info',
    title: 'Capacidade de Sala Atingida',
    description: 'Sala de Reunião atingiu a lotação esperada com 2 participantes ativos.',
    camera: 'CAM 02 - Sala de Reunião',
    read: false,
  },
  {
    id: 'alt-2',
    timestamp: '14:03',
    type: 'info',
    title: 'Identificação Facial Confirmada',
    description: 'Lucas Mendes reconhecido na Recepção com 98% de precisão.',
    camera: 'CAM 03 - Entrada / Recepção',
    read: false,
  },
  {
    id: 'alt-3',
    timestamp: '13:40',
    type: 'info',
    title: 'Check de Perímetro Seguro',
    description: 'Varredura automática da Área Comum sem detecção de anomalias.',
    camera: 'CAM 04 - Área Comum',
    read: true,
  },
];
